// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtiuqlzLO1KgT7kLwex6UZkwKT7BTM8ug',
    appId: '1:354653914173:web:5e2c527ab4b9f4a2a15654',
    messagingSenderId: '354653914173',
    projectId: 'flutter-chatting-app-4e27b',
    authDomain: 'flutter-chatting-app-4e27b.firebaseapp.com',
    storageBucket: 'flutter-chatting-app-4e27b.firebasestorage.app',
    measurementId: 'G-BP4YRVRNNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5TUO8xuF_etrKmPfubCXCuovFPKIcxY',
    appId: '1:354653914173:android:760eaf8fbe6e81d1a15654',
    messagingSenderId: '354653914173',
    projectId: 'flutter-chatting-app-4e27b',
    storageBucket: 'flutter-chatting-app-4e27b.firebasestorage.app',
  );
}
